%% Import data from text file.
% Script for importing data from the following text file:
%
%    E:\MASTER\CUATRI_2\2.4_Inteligencia_Computacional\p1\iris.data
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/02/12 15:43:56

%% Initialize variables.
filename = 'E:\MASTER\CUATRI_2\2.4_Inteligencia_Computacional\Practicas\p0\iris.data';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Sepal_Length = dataArray{:, 1};
Sepal_Width = dataArray{:, 2};
Petal_Length = dataArray{:, 3};
Petal_Width = dataArray{:, 4};
Iris_type = dataArray{:, 5};

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

INPUTS=[Sepal_Length, Sepal_Width, Petal_Length, Petal_Width];
OUTPUTS=Iris_type;
[NumData, Classes]=size(INPUTS);
[NumClass, c]=size(unique(OUTPUTS));
save('irisVars', 'INPUTS', 'OUTPUTS', 'NumClass', 'NumData')
%fitcdiscr